spring:
  application:
    name: userservice

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log-path: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${redis_host:localhost}
      port: ${redis_port:6379}

  logging:
    level: INFO

